services:
  db:
    image: postgres:16
    container_name: medilink_db
    environment:
      POSTGRES_USER: medilink
      POSTGRES_PASSWORD: medilinkpw
      POSTGRES_DB: medilink
    ports:
      - "5432:5432"
    volumes:
      - medilink_pg:/var/lib/postgresql/data
volumes:
  medilink_pg:
