services:
  db:
    image: postgres:16
    container_name: medilink_db
    environment:
      POSTGRES_USER: medilink
      POSTGRES_PASSWORD: medilinkpw
      POSTGRES_DB: medilink
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - medilink_pg:/var/lib/postgresql/data

volumes:
  medilink_pg:
